import os


OPEN_BUS_SIRI_STORAGE_ROOTPATH = os.environ.get('OPEN_BUS_SIRI_STORAGE_ROOTPATH') or '.data/siri'
OPEN_BUS_SIRI_ETL_ROOTPATH = os.path.join(OPEN_BUS_SIRI_STORAGE_ROOTPATH, 'etl')

OPEN_BUS_STRIDE_PUBLIC_S3_BUCKET_NAME = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_BUCKET_NAME') or 'openbus-stride-public'
OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_ACCESS_KEY_ID = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_ACCESS_KEY_ID')
OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_SECRET_ACCESS_KEY = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_SECRET_ACCESS_KEY')
